### ISSUE TITLE
How to add pagination?

### ISSUE THREAD

**Issue by sudarshang** [greglobinski/gatsby-starter-hero-blog#1]
Thanks a lot for this starter. I am migrating my Jekyll blog to this starter, but I am stuck with figuring out how to handle pagination. 

I want to display the excerpts from the latest 10 posts on the index page and add a link to older posts on the index page. The older posts link should link to route path of page2 with the preceding 10 posts.

**Comment by greglobinski** [comment]
@sudarshang 
There are plugins for pagination
https://www.npmjs.com/package/gatsby-paginate
https://www.npmjs.com/package/gatsby-pagination

**Comment by gazpachu** [comment]
@greglobinski First of all, great work, man! :)

I'm struggling to add the pagination :( I've tried both plugins but I see no difference. I still get the fill list of posts. This is how I'm doing it in `gatsby-node.js`:

```
const items = result.data.allMarkdownRemark.edges;

createPaginationPages({
          createPage: createPage,
          edges: items,
          component: indexPage,
          limit: 5
        });
```

Any idea of what I'm doing wrong? I'm still learning about Gatsby. Cheers in advance!
