### ISSUE TITLE
Contact form not working with netlify

### ISSUE THREAD

**Issue by gouravsood** [greglobinski/gatsby-starter-hero-blog#11]
Contact form is not working with netlify because the name attribute on Form and Form.item's input is missing.

**Comment by gouravsood** [comment]
@greglobinski  submitted https://github.com/greglobinski/gatsby-starter-hero-blog/pull/12 pull request for this quick change.

**Comment by greglobinski** [comment]
@gouravsood,
why do you claim it's not working?
I've just sent a message from https://gatsby-starter-hero-blog.greglobinski.com/contact/ and I got it.
So what's the problem?

**Comment by gouravsood** [comment]
I am not sure how its working on your sample blog with name attributes. 

It was not working for me and after looking at "Troubleshooting tips" on https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/, added name for form and form.item inputs. That resolved the issue for me.

**Comment by greglobinski** [comment]
@gouravsood 

it's a flaw, that I omitted the `name` attributes for the form elements, so sure I'll merge the PR in the evening, just curious why it works on the demo site. 

Thanks you
