### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by Kinetic27** [greglobinski/gatsby-starter-hero-blog#111]
I'm just typing
`gatsby new kinetic-gitblog https://github.com/greglobinski/gatsby-starter-hero-blog.git`
and
`gatsby develop`
but infinite loading

`❯ gatsby develop
success open and validate gatsby-configs - 0.107s
success load plugins - 14.398s
warn The Google Analytics plugin requires a tracking ID. Did you mean to add it?
success onPreInit - 0.074s
success initialize cache - 0.022s
success copy gatsby files - 1.850s
warn gatsby-plugin-feed was initialized in gatsby-config.js without a title in a feed.
This means that the plugin will use the default feed title, which may not match your use case.
This behavior will be removed in the next major release of gatsby-plugin-feed.
For more info, check out: https://gatsby.dev/adding-rss-feed
success createSchemaCustomization - 0.497s
success building schema - 0.463s
success createPages - 0.101s
success createPagesStatefully - 0.157s
success updating schema - 0.075s
success onPreExtractQueries - 0.003s
warn Using the global `graphql` tag is deprecated, and will not be supported in v3.
Import it instead like:  import { graphql } from 'gatsby' in file:
E:/Project/GitPage/Gatsby/gatsby-starter-hero-blog-master/node_modules/gatsby-plugin-algolia/example/src/layouts/index.js
success extract queries from components - 1.155s
warn The GraphQL query in the non-page component
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — https://graphql.org/learn/queries/#fragments
success write out requires - 0.137s
success write out redirect data - 0.014s
success Build manifest and related icons - 0.013s
success onPostBootstrap - 0.045s
info bootstrap finished - 26.343s
success run static queries - 0.236s - 1/1 4.23/s
warn code block or inline code language not specified in markdown. applying generic code block
success run page queries - 6.488s - 27/27 4.16/s
[============================]   28.847 s 549/550 100% Generating image thumbnails`

`[============================]   28.847 s 549/550 100% Generating image thumbnails`

It's not going any further here.

gatsby build is same...

**Comment by jianxungao** [comment]
I got the same issue.

**Comment by danielcdai** [comment]
Same issue here...

**Comment by Leobl** [comment]
Same here...

**Comment by easybird** [comment]
Had the same issue, it is related to the https://github.com/giuseppeg/styled-jsx-plugin-postcss/ plugin.

Exact issue is explained here: https://github.com/gatsbyjs/gatsby/issues/21885

Problem is a combination of this package styled-jsx-plugin-postcss + node version 12.x.

Quick solution: lower your node version.
