### ISSUE TITLE
Hit.js : Missing prop

### ISSUE THREAD

**Issue by comxd** [greglobinski/gatsby-starter-hero-blog#17]
The last commit 734398178bccf19dda972235e0429f97145052dd (file **src/components/Search/Hit.js**) now throw an error:

```
index.js:2177 Warning: Failed prop type: The prop `to` is marked as required in `GatsbyLink`, but its value is `undefined`.
```

**Comment by greglobinski** [comment]
@comxd 
Show me on demo which page throws an error https://gatsby-starter-hero-blog.greglobinski.com/category/sayings and which link doesn't work because if `to` is undefined the link should be broke.

**Comment by comxd** [comment]
ooops! sorry
