### ISSUE TITLE
Parent/children article relations

### ISSUE THREAD

**Issue by comxd** [greglobinski/gatsby-starter-hero-blog#19]
Hi,

In a context of question/answer**s** articles like a forum, I want to display/merge all articles located in a subdirectory of the current "post".

My folders structure:

```
/content/posts/YYYY-mm-dd--my-article
/content/posts/YYYY-mm-dd--my-article/solutions/YYYY-mm-dd--my-first-solution
/content/posts/YYYY-mm-dd--my-article/solutions/YYYY-mm-dd--my-second-solution
/content/posts/YYYY-mm-dd--my-article/solutions/YYYY-mm-dd--another-solution
/content/posts/YYYY-mm-dd--my-article/solutions/YYYY-mm-dd--my-test
```

I need to have only one url for the parents posts ("/content/posts/YYYY-mm-dd--my-article"). This parent article will have to display at the bottom the solutions found in the subdirectory "/content/posts/YYYY-mm-dd--my-article/solutions/".

What is the best way?
1. should I merge articles at the time of creation (`exports.onCreateNode`, `exports.createPages`)
1. create a parent/child relation between articles 
1. use the mapping node types (https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types)

**Comment by greglobinski** [comment]
@comxd, I don't think there is something like "the best way". the all ways seam to be eligible.

**Comment by comxd** [comment]
Hi @greglobinski 

I have finally used the createParentChildLink method in the exports.onCreateNode event.

```
const isArticleOfTypeSolution = (nodeId) => {
  return nodeId && nodeId.indexOf("/solutions/") !== -1;
};

const getParentArticleId = (nodeId) => {
  if(isArticleOfTypeSolution(nodeId)){
    const regex = /(\/solutions\/.*)index\.md/u;
    const subst = `/index.md`;
    const parentId = nodeId.replace(regex, subst);

    return parentId;
  }

  return false;
};

exports.onCreateNode = ({ node, getNode, getNodes, boundActionCreators }) => {
// ...
if (node.internal.type === `MarkdownRemark`) {

    const parentId = getParentArticleId(node.id);

    // article of type "solution"?
    if(parentId){
      // set the parent/child node relation
      const parentNode = getNode(parentId);
      createParentChildLink({parent: parentNode, child: node});
    }
}
// ...
};

// in the exports.createPages I simply prevent the creation of the page if the article is a type of "solution".
```
