### ISSUE TITLE
avatar.jpg

### ISSUE THREAD

**Issue by Carbone13** [greglobinski/gatsby-starter-hero-blog#25]
there's the issue when i'm trying to develop hero blog app using terminal . 

i have no idea with this error , because i has tried to change the path and the issued still same .

![Image of Yaktocat](https://i0.wp.com/image.prntscr.com/image/NeXuIVaUS9GUH-SN7jf7yw.png)

**Comment by greglobinski** [comment]
@Carbone13 
Have you tried to clear .cache and public folders?
