### ISSUE TITLE
How to upgrade styled-jsx to 3.0.2?

### ISSUE THREAD

**Issue by sedubois** [greglobinski/gatsby-starter-hero-blog#26]
I tried to upgrade this dependency in this project but encounter strange issues. I see in  `gatsby-config` that you wrote "the [gatsby-plugin-styled-jsx] plugin's code is inserted directly to gatsby-node.js and gatsby-ssr.js files". Could you explain why that was needed and would you know of any method to upgrade styled-jsx to latest? Thank you 🙏

**Comment by greglobinski** [comment]
@sedubois 
No special reason why I did it this way. Just experimented with new stuff and wanted to use it directly not with plugins. You can remove plugins code from gatsby-node and gatsby-ssr and add set them in gatsby-config.

I've just upgraded styled-jsx to the latest 3.0.2  on my localhost and the starter works without any breaking issue.

What kind of issue did you encounter?

**Comment by sedubois** [comment]
OK, I was just confused by that code, and also by all the new logs which looked like an infinite loop:
```
[styled-jsx] Loading plugin from path: styled-jsx-plugin-postcss
[styled-jsx] Loading plugin from path: styled-jsx-plugin-stylelint
[styled-jsx] Loading plugin from path: styled-jsx-plugin-postcss
[styled-jsx] Loading plugin from path: styled-jsx-plugin-stylelint
[styled-jsx] Loading plugin from path: styled-jsx-plugin-postcss
[styled-jsx] Loading plugin from path: styled-jsx-plugin-stylelint
[styled-jsx] Loading plugin from path: styled-jsx-plugin-postcss
[styled-jsx] Loading plugin from path: styled-jsx-plugin-stylelint
[styled-jsx] Loading plugin from path: styled-jsx-plugin-postcss
```

And now for some reason these logs aren't showing up anymore either. Dark magic ... (but at least one other person saw them: https://github.com/zeit/styled-jsx/issues/480)

I will try to use `gatsby-plugin-styled-jsx@2.0.6` after upgrading Gatsby to v2, as it seems to use the v2 API (`onCreateBabelConfig`).
