### ISSUE TITLE
Update to GatsbyJS 2

### ISSUE THREAD

**Issue by ReidWeb** [greglobinski/gatsby-starter-hero-blog#32]
[GatsbyJS v2 has just been released](https://www.gatsbyjs.org/blog/2018-09-17-gatsby-v2/) - it'd be great if this project supported v2.

**Comment by greglobinski** [comment]
Yup, but I have no time for that now, although bumping the starter to v.2 should not be so hard.

**Comment by mohsenkhanpour** [comment]
@greglobinski 
I am trying to update to v2 based on GatsbyJS migration docs, I have updated the dependencies, and removed deprecated dependencies and APIs, however the migration doc lacks depth and I am having issues for some parts:
1. The layout: According to the docs we should wrap children of pages with `<Layout></Layout>` now as we are importing `<ThemeContext.Consumer>` and wrapping the children inside it would it be necessary to wrap `<ThemeContext.Consumer>` inside `<Layout>` component?
2. In gatsby-node.js we have:
```
exports.modifyWebpackConfig = ({ config, stage }) => {
  switch (stage) {
    case "build-javascript":
      {
        config.plugin("BundleAnalyzerPlugin", BundleAnalyzerPlugin, [
          {
            analyzerMode: "static",
            reportFilename: "./report/treemap.html",
            openAnalyzer: true,
            logLevel: "error",
            defaultSizes: "gzip"
          }
        ]);
```

and following the instructions from the docs I changed it to this:
```
exports.onCreateWebpackConfig = ({
  stage,
  rules,
  loaders,
  plugins,
  actions,
}) => { switch (stage) {
  case `build-javascript`:

  actions.setWebpackConfig({
    module: {
      rules: [
        {   test: /\.less$/,
            use: [
              analyzerMode: "static",
              reportFilename: "./report/treemap.html",
              openAnalyzer: true,
              logLevel: "error",
              defaultSizes: "gzip"
          ],
        },
      ],
    },
    plugins: [[BundleAnalyzerPlugin],
      plugins.define({
        __DEVELOPMENT__: stage === `develop` || stage === `develop-html`,
      }),
    ],
    loaders: [
      {
        test: /\.yaml$/,
        include: path.resolve('data'),
        loader: 'yaml',
      },
    ] 
  })
}}
```
I am getting an error at `analayzerMode: "static"`
`unexpected token :`
What am I doing wrong?
3. Another question that I have is about `modifyBabelrc` :

According to the docs I should change like this:
```
- exports.modifyBabelrc = ({ babelrc }) => {
-   return {
-     ...babelrc,
-     plugins: babelrc.plugins.concat([`foo`]),
-   }
+ exports.onCreateBabelConfig = ({ actions }) => {
+   actions.setBabelPlugin({
+     name: `babel-plugin-foo`,
+   })
}
```
However instead of a string like `foo` we have list of plugins with some options, where should we apply the `rules` and `style` etc...
4. In `pages\index.js` we have:
```
    bgDesktop: imageSharp(id: { regex: "/hero-background/" }) {
      resize(width: 1200, quality: 90, cropFocus: CENTER) {
        src
      }
    }
```
Gatsby 2 doesn't use ids anymore and it throws an error, I couldn't find the proper documents to change this part.

If you help me with these issues I will submit a PR for v2 Hero Starter blog.

**Comment by mohsenkhanpour** [comment]
Dear @greglobinski I submitted some PRs regarding Gatsby v2 implementation. I have some more changes (regarding `sizes` being changed to `fluid` etc...) but I will hold them until you merge these PRs to avoid conflict.
Sorry about the high number of PRs (I was new to the workflow), I will submit the next changes as a single PR containing several commits.

**Comment by mohsenkhanpour** [comment]
Dear @greglobinski I submitted a PR containing changes that had to be done according to Gatsby v2 migration guide.
If you help me with the problems that I expressed in the previous comment, I think this starter will be ready to use.
Also sorry about earlier PRs (which I closed in order to submit one unified PR to avoid conflicts), I was somehow new to the workflow.

**Comment by greglobinski** [comment]
@mohsenkhanpour , 
Thank you for closing all this micro PRs :) 
I will create a new dev branch, review and merge you PR to it, so we can work on it further, but it will be probably only after weekend.

**Comment by mohsenkhanpour** [comment]
### Migrating from v1 to v2 (according to [Gatsbyjs.org](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/))

- [x] Update Gatsby version ( [b4e56bc](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/b4e56bc7dc5a439bd110eb241494c5ead18e0ae5))
- [x] Manually install React ( [b4e56bc](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/b4e56bc7dc5a439bd110eb241494c5ead18e0ae5))
- [x] Remove or refactor layout components
- [x] Change `navigateTo` to `navigate` ( [e8c6ddd](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/e8c6ddd1f563789e53b9dcd039a3fae93d5c81a6) )
- [x] Convert to either pure CommonJS or pure ES6 ( [cc4cfb9](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/cc4cfb9a1071dd2ed145724a2d3c15f5ccc27aa7), [7c0c222](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/7c0c222155eddc63b8534a25e3d34e8d365b1fb1) )
- [x] Don’t query nodes by ID ([3849530](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/384953038aac376f6ca678423bea344f267597db))
- [x] Import `Link` from `Gatsby`( [920538c](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/920538c81bc773751c74e8228b750dfa432d38fb) )
- [x] Import `graphql` from `Gatsby` ([daadf3d](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/daadf3d12c26686636eb60a72c24aadf5ec8daa5))
- [x] Rename `boundActionCreators` to `actions` ( [09ce49c](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/09ce49c619f5397e98258693a53a938522386810))
- [x] Rename `pathContext` to `pageContext` ( [48e0a78](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/48e0a789382d78cf7a273e0b596b3f6ab94c71bf) )
- [x] Rename responsive image queries ([07c4310](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/07c431039199f49fe411d10098bd8a68a5623dbd))
- [x] Change `modifyBabelrc` to `onCreateBabelConfig` ([627acc3](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/627acc3eae9130898a515ef70b0b86440233cb56))
- [x] Change `modifyWebpackConfig` to `onCreateWebpackConfig`  ([627acc3](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/627acc3eae9130898a515ef70b0b86440233cb56))
- [x] Update `react-icons` imports ([bed4426](https://github.com/greglobinski/gatsby-starter-hero-blog/pull/45/commits/bed4426d5cb5324fe9deec4b649b4aa4bf972bcb))

#### Updates:
@greglobinski 
There are two ways to do the layout refactoring:
 1. Implementing Gatsby v2 recommendation of turning `Layout` to a normal component. 
 2. Using a plugin called `gatsby-plugin-layout` and keep the layout structure.

I tried both of them but couldn't get them to work (an error about `<LocationProvider>` was logged in both approaches and it is probably related to how pages are the higher level components now and how we pass data from pages to `Layout`.) so I **didn't push** any commits regarding the refactoring of the layout. However what is worth noting is that we should pass data using `<StaticQuery>` in components, templates, and layout even when we are using the layout plugin.

**Comment by greglobinski** [comment]
@mohsenkhanpour 

I created a new branch [v2-wip](https://github.com/greglobinski/gatsby-starter-hero-blog/tree/v2-wip) (work in progress) and merged your PR into it. We will work on this branch till it will be fully functional. 

You upgraded in `package.json` many packages which are not connected with Gatsby upgrade. Especially many of `devDependencies`, some of them are major upgrades. I don't think it's a good practice, too many changes at once can make the job harder. I brought them back to theirs 'original' versions. 

The work is in progress, but the home page and pages, with some style issues should render with `gatsby develop`. Posts pages needs proper babel setup to render, which I have not touched yet.

I made some changes, [here and there](https://github.com/greglobinski/gatsby-starter-hero-blog/commits/v2-wip), the main one is installation of `gatsby-plugin-layout` and refactoring `Layout` component to `StaticQuery`.

**Comment by greglobinski** [comment]
@mohsenkhanpour 
> However what is worth noting is that we should pass data using <StaticQuery> in components, templates, and layout even when we are using the layout plugin.

No, we use `StaticQuery` to query data in "non page" component, with "page" components like `pages/index.js` or template components we still us GraphQL as with v1.

**Comment by mohsenkhanpour** [comment]
@greglobinski 

> No, we use StaticQuery to query data in "non-page" component, with "page" components pages/* or templates/* we still us GraphQL the same way.

According to the docs Templates are similar to "page" components, however I was getting this logged into my terminal so I thought we should use `StaticQuery` with them: 
![image](https://user-images.githubusercontent.com/28626829/46049095-767cff00-c139-11e8-8315-dcce4939fbae.png)
However I downloaded  the v2-wip branch and built with your changes, and I didn't get the warning anymore.
As you mentioned markdown "pages" are loading just fine, and blog posts throw error in browser console:
![image](https://user-images.githubusercontent.com/28626829/46049287-66b1ea80-c13a-11e8-8209-7aa40ebdd3ec.png)
This is the same error that I told you about in my previous comment, and it probably has to do passing the location to `layout` from `page`:
![image](https://user-images.githubusercontent.com/28626829/46049345-aa0c5900-c13a-11e8-8f16-8cd66127e7e2.png)

> The 'post' pages need proper babel setup to render, which I have not touched yet.

I am fairly new to Gatsby/Babel and I don't know how to help you with this, I am also sorry for upgrading too many dependencies.  If there is anything I can help you with just tell me.

**Comment by greglobinski** [comment]
@mohsenkhanpour 

Sure, you can take care of a couple of things:

- the hover effect on blog items (on Home page) is broken, the images scale but seems that the container with `overflow:hidden` disappeared?
- upgraded react-icons are different, in most cases it's ok, but could you fix the positioning the arrow visible after hovering the blog item on Home page, and make it fatter?
- update html.js to the v2., the existing one is build on the `.cache/default-html.js` of v.1, the v2 is much clean, so please fix this, but do not remove the 'apple' tags I added to the `default-html.js`

If you will have questions, ask.

**Comment by mohsenkhanpour** [comment]
@greglobinski 

1. I made the arrow a little fatter (added stroke). 👌

![image](https://user-images.githubusercontent.com/28626829/46089370-2d6d8f00-c1bb-11e8-8943-dbbebb6a6bca.png)

2. It seems that the container with `overflow:hidden` was removed in Gatsby v2. I did some research: 
![image](https://user-images.githubusercontent.com/28626829/46089468-6a398600-c1bb-11e8-8949-32975b02ec1c.png)

![image](https://user-images.githubusercontent.com/28626829/46089498-80dfdd00-c1bb-11e8-9b26-53021c033e43.png)

More info [here](https://github.com/gatsbyjs/gatsby/pull/7826)
Should I add radius to this image to make it a little round? Or do we need to add an outer wrapper of ourselves?

3. I will update html.js to v2 later tonight and submit a PR.

**Comment by greglobinski** [comment]
@mohsenkhanpour 
1. great, move the arrow a little bit down, so it will be centered with the text row.
2. yes,  add a `<div>` wrapper around the `<Img` with `gatsby-image-outer-wrapper` class, that should fix the problem

**Comment by greglobinski** [comment]
I update `v2-wip` branch. The post pages should work.

**Comment by mohsenkhanpour** [comment]
@greglobinski 
![image](https://user-images.githubusercontent.com/28626829/46108583-442bda00-c1eb-11e8-8133-8d331bc8b3ec.png)
My changes are up too. [Here.](https://github.com/mohsenkhanpour/gatsby-starter-hero-blog/tree/v2-wip)
How I can submit a pull request without conflict?

**Comment by greglobinski** [comment]
@mohsenkhanpour You should be able to PR your 2 commitsto `v2-wip` without any conflicts, I did not touch the files you changed.

**Comment by mohsenkhanpour** [comment]
@greglobinski 	It shows a conflict because html.js was renamed.

**Comment by greglobinski** [comment]
@mohsenkhanpour OK, I will take care of it tomorrow

**Comment by mohsenkhanpour** [comment]
Dear @greglobinski , I resolved the issue and submitted a PR.  🙏
I guess v2 is quite feasible now. Thanks. If there is anything else I can help with please do let me know.
I need your opinion on something though: I want to add i18n to this starter, and one of the languages is RTL, what do you think is an optimized way of handling layout and content? 
During my experiments I found that simply adding `direction:rtl` to `layouts\index.js` suits my purpose, but provided that we use `gatsby-plugin-layout` I suppose I can't use two layout files?

**Comment by greglobinski** [comment]
@mohsenkhanpour Thank you.

I have no experience with RTL, but that's what I would try.

I would add a variable `direction` the Layout's `state` and according to its value update the global style in `Layout`, the same way as it's done for the fonts now.

```
                      body {
                        font-family: ${this.state.font400loaded
                          ? "'Open Sans', sans-serif;"
                          : "Arial, sans-serif;"};
                      }
```
Of course if, the RTL language needs its own web fonts you have to refactor fonts conditioning also.

If you will automatically apply the proper language style (I'm not sure if there is a reliable way to do that :)), the logic of this will be of course in `Layout`, but if a user needs to be able to change language setting by hand you have to implement the feature to update `direction` from outside the `Layout` (for example from `Header`) through the React Context API. To do that the Context provider must make it possible.  The `gatsby-plugin-layout`'s [README](https://www.gatsbyjs.org/packages/gatsby-plugin-layout/#passing-data-from-layout-to-page--from-page-to-layout) shows how to create such a provider.

I will soon merge the `v2-wip` with master branch, so the starter will be officially upgraded :)

Thank you for your help!

**Comment by mohsenkhanpour** [comment]
@greglobinski You are welcome, I learned a lot while doing this so thank you too!  
I would be willing to help you bump `gatsby-starter-personal-blog` to v2 too later when we both have free time. Your starters are really beautiful. Great work. Keep up the good work! 👌
I will try what you said and if I have any questions I will open an issue. Thanks for your comment.

**Comment by greglobinski** [comment]
I've merged `v2-wip` into the master, so the starter is officially Gatsby v2 starter. The original version is preserved as the `gatsby-v1` branch.

**Comment by ReidWeb** [comment]
Awesome stuff guys, thanks so much for the turn around on this!

I'm getting a few errors locally however when I attempt to import an svg file and use it in my component. Has something changed with the loader behaviour?

**Comment by nagi1** [comment]
> Dear @greglobinski , I resolved the issue and submitted a PR. 
> I guess v2 is quite feasible now. Thanks. If there is anything else I can help with please do let me know.
> I need your opinion on something though: I want to add i18n to this starter, and one of the languages is RTL, what do you think is an optimized way of handling layout and content (fonts and markdown `pages`)?
> During my experiments I found that simply adding `direction:rtl` to `layouts\index.js` suits my purpose, but provided that we use `gatsby-plugin-layout` I suppose I can't use two layout files?

I'm trying to add RTL Language which is Arabic to my blog using hero starter. I'm completely new to react - working with vue -  I find it hard If you could point me to a repo or something of how to add i18n and RTL support. Thank you

**Comment by mohsenkhanpour** [comment]
@Nagi Gatsby repo has a pretty solid example on how to add i18n to Gatsby.
You can find it [here ](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-i18n)
To add RTL support, you don't really need another layout, you can simply add `dir=rtl` attribute to the html element when you are handling your locale change.

**Comment by nagi** [comment]
@nagi1 :point_up:

**Comment by nagi1** [comment]
> @nagi1

what's the odds!!! XD
