### ISSUE TITLE
Generate webp version for image included in blog post

### ISSUE THREAD

**Issue by sudarshang** [greglobinski/gatsby-starter-hero-blog#4]
Some of the photos are being used both as cover images and as an image in the blog post itself. For example photo-1465070845512-2b2dbdc6df66.jpg

While the cover image gets converted to webp format, the image referenced in the markdown does not get converted to webp. To reproduce this visit 

https://gatsby-starter-hero-blog.greglobinski.com/like-nonsense/

with chrome and see that 

https://gatsby-starter-hero-blog.greglobinski.com/static/photo-1465070845512-2b2dbdc6df66-c05f925825606e19a957283ac76dc0db-78f2b.jpg

is being served.

Is this because gatsby-remark-images does not support conversion to webp?

**Comment by greglobinski** [comment]
@sudarshang 
That's right
