### ISSUE TITLE
Links appear to be relative to wrong path?

### ISSUE THREAD

**Issue by ReidWeb** [greglobinski/gatsby-starter-hero-blog#49]
### Description of issue

All links appear to be at the wrong path? No images are loading and clicking into a blog post directs me to `file:///like-nonsense/` 

Console contains
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
/0-067ffbf84475de1245af.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/app-de082f38ed40841d58e2.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/webpack-runtime-badb468db46fb0ce5ffc.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/static/d/63/path---index-6a9-I4rDurvWWt6rku0yEH9RUAzE6E.json:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
hero-background-9776b7ad0606e1257d99b5f68f0bf6dc-36d59.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```

### Reproduction Steps

1. perform fresh clone of `master` branch
1. run `build` npm task
1. open `public/index.html` in chrome

### Screenshots

![screenshot 2018-09-27 at 22 33 47](https://user-images.githubusercontent.com/3649078/46175932-8ade0a80-c2a5-11e8-9832-ffbf575f9570.png)

![screenshot 2018-09-27 at 22 33 42](https://user-images.githubusercontent.com/3649078/46175935-8d406480-c2a5-11e8-8cab-d8cafd8b2496.png)

**Comment by greglobinski** [comment]
@ReidWeb 

```
gatsby new test00 https://github.com/greglobinski/gatsby-starter-hero-blog.git
...
cd test00
..
gatsby build
...
gatsby serve
...
# open http://localhost:9000 in browser
```
works as it should

**Comment by ReidWeb** [comment]
Sorry, forgot about `gatsby serve` 🤦‍♂️
