### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by b777** [greglobinski/gatsby-starter-hero-blog#50]
Hi, I'm new to gatsby, so not sure if this is a gatsby issue or this theme. I am able to install other starter themes with success. When I run "gatsby new site-name ......." for this theme, it fails with the attached error. This is on a windows PC. I"ve read and performed the steps at https://www.gatsbyjs.org/docs/gatsby-on-windows/ without success.

Any pointers?

![gatsby-error](https://user-images.githubusercontent.com/6910710/46218068-54d27200-c309-11e8-960d-b93403dd7fab.PNG)
![gatsby-error-2](https://user-images.githubusercontent.com/6910710/46218069-54d27200-c309-11e8-84d0-976b8cd3a629.PNG)

**Comment by greglobinski** [comment]
@b777 
>  I am able to install other starter themes with success.
Which?

**Comment by b777** [comment]
The default starter and gatsby-starter-blog-no-styles work.
However, I just went through a few others and they show different types of errors. So it seems something wrong with my pc. 
Any suggestions besides uninstalling everything and re-installing?

**Comment by greglobinski** [comment]
The starters you have no problem with  are starters which do not use Sharp. Your problem is this https://www.gatsbyjs.org/docs/gatsby-on-windows/

**Comment by greglobinski** [comment]
When you will be able to install https://github.com/gatsbyjs/gatsby-starter-blog you can back here and try to install this starter.

**Comment by brodneil** [comment]
Hi

Can you please check. I am getting an error when installing this starter.  For the gatsby starter default ---- i dont have any issue.

![image](https://user-images.githubusercontent.com/31291293/62001870-9f409d00-b12c-11e9-8ac3-e9d6fb795e6e.png)
![image](https://user-images.githubusercontent.com/31291293/62001893-4291b200-b12d-11e9-95ac-119cd9907679.png)


Thank you. Hope you can help.
