### ISSUE TITLE
Form submission issue - Gatsby v2

### ISSUE THREAD

**Issue by leeant06** [greglobinski/gatsby-starter-hero-blog#51]
Minor issue with the the form submission in Gatsby v2
For reference: https://github.com/gatsbyjs/gatsby/issues/7997
Change request: ./scr/components/Contact/Contact.js

line #37: fetch("/", ...) -> fetch("/?no-cache=1", ...)

**Comment by mohsenkhanpour** [comment]
@leeant06 	Does changing that on line 37 solves the problem for you?

**Comment by anlett30js** [comment]
@mohsenkhanpour : By adding ?no-cache=1 as shown above, the problem should be fixed.

**Comment by greglobinski** [comment]
Upgrading gatsby and gatsby-plugin-offline fixed the issue.

**Comment by guiphh** [comment]
Hi guys,

I can't get the form working. 
I've tried the no-cache=1 workaround but it's not working for me.
Is it working for you?

**Comment by guiphh** [comment]
Forget it, it's actually working, don't know why but it took a long time to appear on netlify admin.
