### ISSUE TITLE
Category with space in name links to invalid path

### ISSUE THREAD

**Issue by b777** [greglobinski/gatsby-starter-hero-blog#52]
When I make a post with a category with a space in it like "Las Vegas", the category page is created at /category/Las-Vegas, however, the link within the Post in the meta data links to /category/Las%20Vegas and throws a 404 error for page not found.

How would I fix this so that I can use categories with spaces in them?

Thanks

**Comment by greglobinski** [comment]
@b777 
Refactor the [line](https://github.com/greglobinski/gatsby-starter-hero-blog/blob/3ec5fff16083fb21847acf17eed5ea87da2b5335/src/components/Post/Meta.js#L23). 

```
          <Link to={`/category/${category}`}>{category}</Link>
```

You have to replace spaces inside the `${category}` string with dashes. When you do, you can PR.

**Comment by greglobinski** [comment]
https://github.com/greglobinski/gatsby-starter-hero-blog/pull/56
