### ISSUE TITLE
Path Prefix In Wrong Place In Gatsby-Config, Come On With All That Now, Guyos

### ISSUE THREAD

**Issue by JimTheMan** [greglobinski/gatsby-starter-hero-blog#55]
Crazy kook time trying to deploy to gh-pages because the gatsby-config is not setup correctly. 

In particular, <h1> "pathPrefix" needed to be at the top level of gatsby-config.js, not nested within siteMetadata</h1>

See [this issue](https://github.com/greglobinski/gatsby-starter-hero-blog/issues/54) if you feel like it. 

thanks fam

**Comment by greglobinski** [comment]
I moved pathPrefix to root level of config but also commented it because it cannot be empty.
