### ISSUE TITLE
meta property og:image not set correctly

### ISSUE THREAD

**Issue by b777** [greglobinski/gatsby-starter-hero-blog#58]
Hi,
It looks like the og:image property is not set correctly to display an image when sharing a post on Facebok. 

It outputs the below for articles:
`<meta property="og:image" content="[object Object]" data-react-helmet="true">`

I believe the content should be a direct URL to the image file.

I've looked at the code, but I'm not familiar enough with react on the best way to fix this. It's being set in the seo.js file, but I'm not sure how to take the postCover const and make it a URL to the image file.

**Comment by greglobinski** [comment]
@b777 take a look at Seo.js at Personal Blog starter https://github.com/greglobinski/gatsby-starter-personal-blog

**Comment by b777** [comment]
i submitted a pull request to fix
