### ISSUE TITLE
Any plan on adding pagination?

### ISSUE THREAD

**Issue by ZacharyChim** [greglobinski/gatsby-starter-hero-blog#60]
Hi, I'm new to Gatsby and this is a great starter. But when there are more posts, all blog posts are stacked on the index page. I wonder if there is any plan to add pagination. I am trying to figure it out with the https://github.com/GatsbyCentral/gatsby-awesome-pagination plugin, but it's not as easy as I thought.

**Comment by ZacharyChim** [comment]
I tried following the tutorial on Gatsbyjs.org: https://www.gatsbyjs.org/docs/adding-pagination/ , using src/pages/index.js as blog-list-template, but ended up with a context error: not able to pass $limit & $skip

**Comment by greglobinski** [comment]
@ZacharyChim Sorry I have no time for implementing new features to the starter now, maybe later. 
Take a look at this https://greglobinski.github.io/gatsby-starter-kit-docs/clean-diary-starter/
