### ISSUE TITLE
How to improve performance?

### ISSUE THREAD

**Issue by shinyaK14** [greglobinski/gatsby-starter-hero-blog#68]
Do you have any ideas to improve performance? Especially for the first load time?

My blog has 250 pages. When I look at performance, everything looks good except First Byte Time.
It takes around 8 seconds.

Do you have any idea to solve?

<img width="438" alt="screen shot 2018-11-29 at 21 26 04" src="https://user-images.githubusercontent.com/9897663/49250127-5cec8200-f41e-11e8-9a4d-8d33c9915fb8.png">
<img width="723" alt="screen shot 2018-11-29 at 21 26 14" src="https://user-images.githubusercontent.com/9897663/49250132-5f4edc00-f41e-11e8-901d-663f9054a84e.png">

**Comment by greglobinski** [comment]
On what kind of network do you testing, how looks the repeat view, where do you deploy your site. Or just give me a link to your site.

**Comment by shinyaK14** [comment]
@greglobinski  Thank you for your reply!

My blog url is https://pensive-jennings-e771dc.netlify.com/
I'm testing here https://www.webpagetest.org/result/181204_ZH_84b3972b2771a4664b028a39fc1ae9a1/
I deployed to Netlify.

1900 ms First Byte Time. Do you have a suggestion?

**Comment by greglobinski** [comment]
That's what I get
https://www.webpagetest.org/result/181204_MP_fb787c588bc6ed79d3fb44f2e520500c/

A server responding time is not a constant value, so you can't base on one measurement.

**Comment by shinyaK14** [comment]
@greglobinski Got it. Thanks!
