### ISSUE TITLE
Local npm install fails

### ISSUE THREAD

**Issue by scottwalstead** [greglobinski/gatsby-starter-hero-blog#7]
<img width="1510" alt="screen shot 2018-06-16 at 1 25 39 pm" src="https://user-images.githubusercontent.com/31423150/41502173-e10e536c-7168-11e8-86fe-fe7d552c9070.png">

**Comment by gouravsood** [comment]
Duplicate of https://github.com/greglobinski/gatsby-starter-hero-blog/issues/5. Please see the latest comments on this issue.
