### ISSUE TITLE
Blockquotes is not working in md files

### ISSUE THREAD

**Issue by gouravsood** [greglobinski/gatsby-starter-hero-blog#9]
Blockquotes is not working in md files. 

**Post contains the Blockquotes text:**

> Proin ornare ligula eu tellus tempus elementum. Aenean bibendum iaculis mi, nec blandit lacus interdum vitae. Vestibulum non nibh risus, a scelerisque purus. Ut vel arcu ac tortor adipiscing hendrerit vel sed massa. Fusce sem libero, lacinia vulputate interdum non, porttitor non quam. Aliquam sed felis ligula. Duis non nulla magna.

![image](https://user-images.githubusercontent.com/4436378/41624065-e961d39e-7457-11e8-9218-5b1765b1c85d.png)

But the output is not generated as 'Blockquotes'
![image](https://user-images.githubusercontent.com/4436378/41624097-fe50df98-7457-11e8-8020-fcde2a5d9588.png)

Sample blog deployed here:
https://compassionate-kowalevski-449a27.netlify.com/two-things-are-infinite/

**Comment by greglobinski** [comment]
@gouravsood, 
they are working, there is simply not a style for the tag. But it's not the only tag for which I did not set the style. If you need an inspiration to style it take a look at [PersonalBlog](https://github.com/greglobinski/gatsby-starter-personal-blog)

**Comment by gouravsood** [comment]
Thanks for the reference @greglobinsk. Shouldn't be there some default styling of Blockquotes as done by the markdown.

**Comment by greglobinski** [comment]
@gouravsood
no the markdown does not add any default styling. There are default styles for `<blockquotes>` in  web browsers, but they only add indentation by setting `margin-left` which is overridden by the starter's global styles in `src/layouts/index.js` file 
```
              <style jsx global>{`
                html {
                  box-sizing: border-box;
                }
                *,
                *:after,
                *:before {
                  box-sizing: inherit;
                  margin: 0;
                  padding: 0;
                }
```

**Comment by gouravsood** [comment]
Thanks @greglobinski for the help. I am able to sort out the styles now.
